// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/alerts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "List recent alerts for a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/alerts.AlertResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Create an alert",
                "parameters": [
                    {
                        "description": "Alert to create",
                        "name": "alert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/alerts.CreateAlertRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/missions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "missions"
                ],
                "summary": "List missions for a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/missions.MissionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "missions"
                ],
                "summary": "Create a mission",
                "parameters": [
                    {
                        "description": "Mission to create",
                        "name": "mission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/missions.CreateMissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/missions.MissionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/missions/{id}/upload": {
            "post": {
                "tags": [
                    "missions"
                ],
                "summary": "Mark a mission as uploaded",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mission ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/telemetry": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get telemetry frames in a time range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle ID",
                        "name": "vehicle_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Range start (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Range end (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/telemetry.TelemetryFrameResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Ingest a telemetry frame",
                "parameters": [
                    {
                        "description": "Telemetry frame",
                        "name": "frame",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/telemetry.IngestTelemetryRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/vehicles": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "List vehicles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vehicles.VehicleResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Create a vehicle",
                "parameters": [
                    {
                        "description": "Vehicle to create",
                        "name": "vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vehicles.CreateVehicleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/vehicles.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/vehicles/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Get a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vehicles.VehicleResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "alerts.AlertResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "severity": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "ts": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "string"
                }
            }
        },
        "alerts.CreateAlertRequest": {
            "type": "object",
            "properties": {
                "severity": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "string"
                }
            }
        },
        "missions.CreateMissionRequest": {
            "type": "object",
            "properties": {
                "geofence_json": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "plan_json": {
                    "type": "object"
                },
                "rally_points_json": {
                    "type": "object"
                },
                "vehicle_id": {
                    "type": "string"
                }
            }
        },
        "missions.MissionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "geofence_json": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "plan_json": {
                    "type": "object"
                },
                "rally_points_json": {
                    "type": "object"
                },
                "uploaded_at": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "string"
                }
            }
        },
        "telemetry.IngestTelemetryRequest": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "number"
                },
                "armed": {
                    "type": "boolean"
                },
                "battery_pct": {
                    "type": "integer"
                },
                "cpu_pct": {
                    "type": "number"
                },
                "cpu_temp": {
                    "type": "number"
                },
                "current": {
                    "type": "number"
                },
                "disk_pct": {
                    "type": "number"
                },
                "flight_mode": {
                    "type": "string"
                },
                "groundspeed": {
                    "type": "number"
                },
                "heading": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "node_status": {
                    "type": "object"
                },
                "ram_pct": {
                    "type": "number"
                },
                "ts": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "string"
                },
                "voltage": {
                    "type": "number"
                }
            }
        },
        "telemetry.TelemetryFrameResponse": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "number"
                },
                "armed": {
                    "type": "boolean"
                },
                "battery_pct": {
                    "type": "integer"
                },
                "cpu_pct": {
                    "type": "number"
                },
                "cpu_temp": {
                    "type": "number"
                },
                "current": {
                    "type": "number"
                },
                "disk_pct": {
                    "type": "number"
                },
                "flight_mode": {
                    "type": "string"
                },
                "groundspeed": {
                    "type": "number"
                },
                "heading": {
                    "type": "number"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "node_status": {
                    "type": "object"
                },
                "ram_pct": {
                    "type": "number"
                },
                "ts": {
                    "type": "string"
                },
                "vehicle_id": {
                    "type": "string"
                },
                "voltage": {
                    "type": "number"
                }
            }
        },
        "vehicles.CreateVehicleRequest": {
            "type": "object",
            "properties": {
                "firmware": {
                    "type": "string"
                },
                "mavlink_sysid": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "vehicles.VehicleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "firmware": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mavlink_sysid": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GCS API",
	Description:      "Ground Control Station backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
