// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (vehicle_id, severity, text) VALUES ($1, $2, $3)
`

type InsertAlertParams struct {
	VehicleID pgtype.UUID `json:"vehicle_id"`
	Severity  pgtype.Int2 `json:"severity"`
	Text      pgtype.Text `json:"text"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert, arg.VehicleID, arg.Severity, arg.Text)
	return err
}

const listRecentAlerts = `-- name: ListRecentAlerts :many
SELECT id, vehicle_id, ts, severity, text FROM alerts WHERE vehicle_id = $1 ORDER BY ts DESC LIMIT 50
`

func (q *Queries) ListRecentAlerts(ctx context.Context, vehicleID pgtype.UUID) ([]*Alert, error) {
	rows, err := q.db.Query(ctx, listRecentAlerts, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Ts,
			&i.Severity,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
