// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: missions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMission = `-- name: CreateMission :one
INSERT INTO missions (vehicle_id, name, plan_json, geofence_json, rally_points_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vehicle_id, name, plan_json, geofence_json, rally_points_json, created_at, uploaded_at
`

type CreateMissionParams struct {
	VehicleID       pgtype.UUID `json:"vehicle_id"`
	Name            string      `json:"name"`
	PlanJson        []byte      `json:"plan_json"`
	GeofenceJson    []byte      `json:"geofence_json"`
	RallyPointsJson []byte      `json:"rally_points_json"`
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (*Mission, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.VehicleID,
		arg.Name,
		arg.PlanJson,
		arg.GeofenceJson,
		arg.RallyPointsJson,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Name,
		&i.PlanJson,
		&i.GeofenceJson,
		&i.RallyPointsJson,
		&i.CreatedAt,
		&i.UploadedAt,
	)
	return &i, err
}

const listMissionsByVehicle = `-- name: ListMissionsByVehicle :many
SELECT id, vehicle_id, name, plan_json, geofence_json, rally_points_json, created_at, uploaded_at FROM missions WHERE vehicle_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMissionsByVehicle(ctx context.Context, vehicleID pgtype.UUID) ([]*Mission, error) {
	rows, err := q.db.Query(ctx, listMissionsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Mission{}
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Name,
			&i.PlanJson,
			&i.GeofenceJson,
			&i.RallyPointsJson,
			&i.CreatedAt,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissionUploaded = `-- name: MarkMissionUploaded :exec
UPDATE missions SET uploaded_at = now() WHERE id = $1
`

func (q *Queries) MarkMissionUploaded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMissionUploaded, id)
	return err
}
