// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID        int64              `json:"id"`
	VehicleID pgtype.UUID        `json:"vehicle_id"`
	Ts        pgtype.Timestamptz `json:"ts"`
	Severity  pgtype.Int2        `json:"severity"`
	Text      pgtype.Text        `json:"text"`
}

type FlightSession struct {
	ID         pgtype.UUID        `json:"id"`
	VehicleID  pgtype.UUID        `json:"vehicle_id"`
	MissionID  pgtype.UUID        `json:"mission_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	LogFileRef pgtype.Text        `json:"log_file_ref"`
}

type Mission struct {
	ID              pgtype.UUID        `json:"id"`
	VehicleID       pgtype.UUID        `json:"vehicle_id"`
	Name            string             `json:"name"`
	PlanJson        []byte             `json:"plan_json"`
	GeofenceJson    []byte             `json:"geofence_json"`
	RallyPointsJson []byte             `json:"rally_points_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UploadedAt      pgtype.Timestamptz `json:"uploaded_at"`
}

type TelemetryFrame struct {
	VehicleID   pgtype.UUID        `json:"vehicle_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Lat         pgtype.Float8      `json:"lat"`
	Lon         pgtype.Float8      `json:"lon"`
	Alt         pgtype.Float8      `json:"alt"`
	Heading     pgtype.Float8      `json:"heading"`
	Groundspeed pgtype.Float8      `json:"groundspeed"`
	BatteryPct  pgtype.Int2        `json:"battery_pct"`
	Voltage     pgtype.Float8      `json:"voltage"`
	Current     pgtype.Float8      `json:"current"`
	FlightMode  pgtype.Text        `json:"flight_mode"`
	Armed       pgtype.Bool        `json:"armed"`
	CpuPct      pgtype.Float4      `json:"cpu_pct"`
	RamPct      pgtype.Float4      `json:"ram_pct"`
	DiskPct     pgtype.Float4      `json:"disk_pct"`
	CpuTemp     pgtype.Float4      `json:"cpu_temp"`
	NodeStatus  []byte             `json:"node_status"`
}

type Vehicle struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Type         pgtype.Text        `json:"type"`
	Firmware     pgtype.Text        `json:"firmware"`
	MavlinkSysid pgtype.Int4        `json:"mavlink_sysid"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
