// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTelemetryRange = `-- name: GetTelemetryRange :many
SELECT vehicle_id, ts, lat, lon, alt, heading, groundspeed, battery_pct, voltage, current, flight_mode, armed, cpu_pct, ram_pct, disk_pct, cpu_temp, node_status FROM telemetry_frames
WHERE vehicle_id = $1 AND ts BETWEEN $2 AND $3
ORDER BY ts ASC
`

type GetTelemetryRangeParams struct {
	VehicleID pgtype.UUID        `json:"vehicle_id"`
	Ts        pgtype.Timestamptz `json:"ts"`
	Ts_2      pgtype.Timestamptz `json:"ts_2"`
}

func (q *Queries) GetTelemetryRange(ctx context.Context, arg GetTelemetryRangeParams) ([]*TelemetryFrame, error) {
	rows, err := q.db.Query(ctx, getTelemetryRange, arg.VehicleID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TelemetryFrame{}
	for rows.Next() {
		var i TelemetryFrame
		if err := rows.Scan(
			&i.VehicleID,
			&i.Ts,
			&i.Lat,
			&i.Lon,
			&i.Alt,
			&i.Heading,
			&i.Groundspeed,
			&i.BatteryPct,
			&i.Voltage,
			&i.Current,
			&i.FlightMode,
			&i.Armed,
			&i.CpuPct,
			&i.RamPct,
			&i.DiskPct,
			&i.CpuTemp,
			&i.NodeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTelemetryFrame = `-- name: InsertTelemetryFrame :exec
INSERT INTO telemetry_frames (
    vehicle_id, ts, lat, lon, alt, heading, groundspeed,
    battery_pct, voltage, current, flight_mode, armed,
    cpu_pct, ram_pct, disk_pct, cpu_temp, node_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
`

type InsertTelemetryFrameParams struct {
	VehicleID   pgtype.UUID        `json:"vehicle_id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	Lat         pgtype.Float8      `json:"lat"`
	Lon         pgtype.Float8      `json:"lon"`
	Alt         pgtype.Float8      `json:"alt"`
	Heading     pgtype.Float8      `json:"heading"`
	Groundspeed pgtype.Float8      `json:"groundspeed"`
	BatteryPct  pgtype.Int2        `json:"battery_pct"`
	Voltage     pgtype.Float8      `json:"voltage"`
	Current     pgtype.Float8      `json:"current"`
	FlightMode  pgtype.Text        `json:"flight_mode"`
	Armed       pgtype.Bool        `json:"armed"`
	CpuPct      pgtype.Float4      `json:"cpu_pct"`
	RamPct      pgtype.Float4      `json:"ram_pct"`
	DiskPct     pgtype.Float4      `json:"disk_pct"`
	CpuTemp     pgtype.Float4      `json:"cpu_temp"`
	NodeStatus  []byte             `json:"node_status"`
}

func (q *Queries) InsertTelemetryFrame(ctx context.Context, arg InsertTelemetryFrameParams) error {
	_, err := q.db.Exec(ctx, insertTelemetryFrame,
		arg.VehicleID,
		arg.Ts,
		arg.Lat,
		arg.Lon,
		arg.Alt,
		arg.Heading,
		arg.Groundspeed,
		arg.BatteryPct,
		arg.Voltage,
		arg.Current,
		arg.FlightMode,
		arg.Armed,
		arg.CpuPct,
		arg.RamPct,
		arg.DiskPct,
		arg.CpuTemp,
		arg.NodeStatus,
	)
	return err
}
