// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vehicles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (name, type, firmware, mavlink_sysid)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, firmware, mavlink_sysid, created_at
`

type CreateVehicleParams struct {
	Name         string      `json:"name"`
	Type         pgtype.Text `json:"type"`
	Firmware     pgtype.Text `json:"firmware"`
	MavlinkSysid pgtype.Int4 `json:"mavlink_sysid"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (*Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.Name,
		arg.Type,
		arg.Firmware,
		arg.MavlinkSysid,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Firmware,
		&i.MavlinkSysid,
		&i.CreatedAt,
	)
	return &i, err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, name, type, firmware, mavlink_sysid, created_at FROM vehicles WHERE id = $1
`

func (q *Queries) GetVehicle(ctx context.Context, id pgtype.UUID) (*Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Firmware,
		&i.MavlinkSysid,
		&i.CreatedAt,
	)
	return &i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, name, type, firmware, mavlink_sysid, created_at FROM vehicles ORDER BY created_at DESC
`

func (q *Queries) ListVehicles(ctx context.Context) ([]*Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Firmware,
			&i.MavlinkSysid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
